name: Extract Issue Code

on:
  issue_comment:
    types: [created, edited]

jobs:
  extract-issue-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Extract issue code
      run: |
        # Script to extract issue code from the comment body
        python - <<EOF
        import re
        import os

        # Get comment body from the environment variable
        caminho = os.environ['GITHUB_EVENT_PATH']

        with open(caminho, 'wb') as file:
          comment_body = file.read()

        # Define a regular expression to extract the issue code
        pattern = r'Issue NUMBER: (\d+)'

        # Search for the pattern in the comment body
        match = re.search(pattern, comment_body)

        print(str(os.environ['GITHUB_EVENT_PATH']))
        
        if match:
            issue_code = match.group(1)
            print(f"Extracted Issue Code: {issue_code}")
            # You can use the 'issue_code' variable in further actions or steps
        else:
            print("Issue Code not found in the comment body.")
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
