name: Extract Issue Code

on:
  issue_comment:
    types: [created, edited]

jobs:
  extract-issue-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Extract issue code
      run: |
        # Script to extract issue code from the comment body
        python - <<EOF
        import re
        import os
        import json

        # Get event path from the environment variable
        var_strPathEventFile = os.environ['GITHUB_EVENT_PATH']

        # Convert json file to object json
        with open(var_strPathEventFile, 'r') as file:
          var_jsonResponseEvent = json.load(file)

        # Get issue body from the json response
        var_strIssueBody = var_jsonResponseEvent['issue']['body']
        
        # Define a regular expression to extract the issue code
        var_strPatternIssueNumber = r'Issue NUMBER: (\d+)'

        # Search for the pattern in the issue body
        var_matchIssueNumber = re.search(var_strPatternIssueNumber, var_strIssueBody)

        print(var_strIssueBody)
        
        if var_matchIssueNumber:
            var_strIssueNumber = var_matchIssueNumber.group(1)
            print(f"Extracted Issue Number: {var_strIssueNumber}")
            echo "issue_number=$var_strIssueNumber" >> $GITHUB_ENV
            # You can use the 'issue_number' variable in further actions or steps
        else:
            print("Issue Number not found in the issue body.")
        EOF
        echo $issue_number
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
