name: Replace Documents

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Replace Text
        run: |
          find . -name "*.txt" -type f -print0 | xargs -0 sed -i 's/foo/bar/g'
          git config --local user.email "rafael.souza123@fatec.sp.gov.br"
          git config --local user.name "RafaelHPS"
          git commit -a -m "Replace Foo Bar"
          git push https://${{ secrets.MEU_TOKEN }}@github.com/RafaelHPS/rep_clonar.git
