
name: Replace Documents

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Replace Text
        run: |
          dir
          find . -wholename "./setup.py" -type f -print0 | xargs -0 sed -i 's/name="botcity_framework_t2c"/name="{{cookiecutter.nome_projeto}}"/g'
          find . -wholename "./setup.py" -type f -print0 | xargs -0 sed -i 's/description="Framework used by T2C to help develop automations in BotCity"/description="{{cookiecutter.descricao_projeto}}"/g'
          find . -wholename "./setup.py" -type f -print0 | xargs -0 sed -i 's/"framework":/"{{cookiecutter.nome_projeto}}":/g'
          find . -name "framework/*.py" -type f -print0 | xargs -0 sed -i 's/from framework./from {{cookiecutter.nome_projeto}}./g'
          git config --local user.email "rafael.souza123@fatec.sp.gov.br"
          git config --local user.name "RafaelHPS"
          git commit -a -m "Replace nomes do projeto para pode ser usado no cookiecutter"
          git push https://${{ secrets.MEU_TOKEN }}@github.com/RafaelHPS/rep_clonar.git
